# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('stars', models.IntegerField()),
                ('FK_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_book', to='booksapp.Book')),
                ('FK_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='mylogin.Users')),
            ],
        ),
    ]
